version: '3'
services:
  web:
    image: "gcr.io/first-hold-235316/bvp:v4"
    ports:
     - "80:80"
     - "8080:8080"
    environment:
     - CONNECTION_URL=jdbc:postgresql://192.168.2.111:5432/postgres
     - POSTGRESQL_USER=bvp
     - POSTGRESQL_PASSWORD=bvp
